### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by hughwilliams94** [ericdallo/hover.el#9]
I'm having trouble using hover.el with the pGTK wayland emacs branch. When I run `hover-run` the command fails with the following message:
```
hover: Running surf_diary in debug_unopt mode
2021/10/07 11:14:19 PlatformError: X11: Failed to open display wayland-1
panic: NotInitialized: The GLFW library is not initialized

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError({0x0, 0x0, 0x52d0ea})
	/home/hugh/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20201108214237-06ea97f0c265/error.go:174 +0x186
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
	/home/hugh/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20201108214237-06ea97f0c265/error.go:185
github.com/go-gl/glfw/v3.3/glfw.WindowHint(0xc, 0x10006)
	/home/hugh/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20201108214237-06ea97f0c265/window.go:275 +0x3f
github.com/go-flutter-desktop/go-flutter/internal/opengl.GLFWWindowHint()
	/home/hugh/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.43.0/internal/opengl/opengl.go:73 +0x25
github.com/go-flutter-desktop/go-flutter.(*Application).Run(0xc0000e0000)
	/home/hugh/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.43.0/application.go:120 +0x23c
github.com/go-flutter-desktop/go-flutter.Run({0xc0000a6048, 0xc0000a6050, 0x5b0dcc})
	/home/hugh/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.43.0/application.go:26 +0x25
main.main()
	/home/hugh/Builds/surf_diary/go/cmd/main.go:24 +0x199
hover: App 'surf_diary' exited with error: exit status 2

Process Hover exited abnormally with code 2
```
Using `hover run` from the terminal works fine. I have the `glfw-wayland` package installed.

**Comment by ericdallo** [comment]
Oh, that looks like a problem, not sure what we would need to do on hover.el to support that 😔

**Comment by zw963** [comment]
In fact, i use wayland + GNOME in arch linux, hover.el work well for me.

**Comment by hughwilliams94** [comment]
@zw963 Are you using the pgtk fork of emacs?

**Comment by zw963** [comment]
> @zw963 Are you using the pgtk fork of emacs?

Emacs 28 branch latest, i guess pgtk still not merged, right?
